---
extends: standard
parserOptions:
  sourceType: 'script'
rules:
  no-var: 2
  strict: [2, 'safe']
  block-scoped-var: 2
  complexity: 1
  default-case: 2
  dot-notation: 2
  guard-for-in: 2
  linebreak-style: [1, 'unix']
  no-alert: 2
  no-catch-shadow: 2
  no-case-declarations: 2
  no-console: 1
  no-constant-condition: 2
  no-continue: 1
  no-div-regex: 2
  no-else-return: 2
  no-empty: 2
  no-empty-pattern: 2
  no-extra-semi: 2
  no-implicit-coercion: 2
  no-inline-comments: 2
  no-labels: 2
  no-loop-func: 2
  no-mixed-requires: 2
  no-nested-ternary: 1
  no-script-url: 2
  no-shadow: 2
  no-use-before-define: 2
  no-void: 2
  no-warning-comments: 2
  quote-props: [2, 'as-needed']
  require-yield: 2
