language: node_js
node_js:
  - '4'
  - '5'
  - stable

# always use npm latest
before_install:
  - npm i -g npm

addons:
  firefox: 'latest'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
