# Warning: This file is automatically synced from https://github.com/ipfs/ci-sync so if you want to change it, please change it there and ask someone to sync all repositories.
sudo: false
language: node_js

matrix:
  include:
  - node_js: 6
    env: CXX=g++-4.8
  - node_js: 8
    env: CXX=g++-4.8
    #  - node_js: stable
    #    env: CXX=g++-4.8

script:
  - npm run lint
  - npm run test
  - npm run coverage

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm run coverage-publish

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
