environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

init:
  - git config --global core.autocrlf input

# cache:
#  - node_modules

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off

version: "{build}"
